In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# creation of array

list=[1,2,3,4,5,6]
print(list)

## To create numpy array,we first need to import the numpy package:

import numpy as np

array=np.array(list,dtype=int)
print(array)

array=np.array(list,dtype=int)
print(array)

from numpy import *
arr=array([1,2,3,4,5])
print(arr.dtype)
print(arr)

array=np.array(list,dtype=int)
print(array)

print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

array2=array.reshape(2,3)
print(array2)
array2.shape

array3=array.reshape(3,-1)
print(array3)
print(array3.ndim)

## Initializing numpy arrays from nested python lists:-

list2=[1,2,3,4,5]
list3=[2,4,6,8,10]
list4=[3,6,9,7,8]
mul_arr=np.array([list2,list3,list4])
print(mul_arr)
print(mul_arr.shape)

mul_arr.reshape(1,15)

# Numpy Attributes


a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)

## reshaping the ndarray

a.shape=(4,2)
print(a)

a.shape=(2,4)
print(a)





[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
int32
[1 2 3 4 5]
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
6
1
(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
2
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9  7  8]]
(3, 5)
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
