In [1]:
#packages and librays
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#taking data
x=np.array([5,7,2,6,4]).reshape(-1,1)
y=np.array([8,4,6,2,1])

In [3]:
#fitting model
model=LinearRegression().fit(x,y)

In [4]:
#predicting y values for given x values (b0+(b1*x))
y_pre=model.predict(x)


In [5]:
print("predict score:",model.score(x,y_pre))
print("Noraml score:",model.score(x,y))

predict score: 1.0
Noraml score: 0.04746209624258402


In [6]:
#differenece between y predict and given y
print(y_pre)
print(y)

[4.13513514 3.48648649 5.10810811 3.81081081 4.45945946]
[8 4 6 2 1]


In [7]:
#rechecking with formula (bo+(b1*x))
print("b0:",model.intercept_)
print("b1:",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x,axis=1)
print("Rechecked Y predict values:",y_rc)

b0: 5.756756756756758
b1: [-0.32432432]
Rechecked Y predict values: [4.13513514 3.48648649 5.10810811 3.81081081 4.45945946]


In [9]:
#predicting y values for given x_new values(b0+(b1*x))
x_new=np.array([11,12,13,14,15]).reshape(-1,1)
y_new=model.predict(x_new)
print(x_new)
print(y_new)

[[11]
 [12]
 [13]
 [14]
 [15]]
[2.18918919 1.86486486 1.54054054 1.21621622 0.89189189]


In [10]:
print("new predict score:",model.score(x_new,y_new))

new predict score: 1.0
